# Configuració de Docker Compose per a tot el projecte

services:
  db:
    image: mysql:8.0
    container_name: ticketing_db_container
    restart: always
    environment:
      MYSQL_DATABASE: ticketing_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../database/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: ticketing_backend_container
    restart: always
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: ticketing_db
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "node", "-e", "const http = require('http'); const req = http.get('http://localhost:3000/api/estat', (res) => { if (res.statusCode === 200) { process.exit(0); } else { process.exit(1); } }); req.on('error', (err) => { process.exit(1); });" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: ticketing_frontend_container
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.nuxt
    depends_on:
      backend:
        condition: service_healthy

volumes:
  db_data:
